version: 2
updates:
  # PHP (Composer deps)
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"

  # Docker (php, node, postgres)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"

  # GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
