services:
  db:
    volumes:
      - ./sql_files_for_import_tmp:/docker-entrypoint-initdb.d
      - peer_backend_ci-cd_db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - my-network

  backend:
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www/html
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/graphql"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - my-network

  newman:
    build:
      context: .
      dockerfile: Dockerfile.newman
    volumes:
      - ./tests/postman_collection:/etc/newman
      - ./newman/reports:/etc/newman/reports
    entrypoint: []
    command: tail -f /dev/null
    mem_limit: 2g
    networks:
      - my-network

networks:
  my-network:
    external: true

volumes:
  peer_backend_ci-cd_db-data:
    external: true
