FROM postman/newman:alpine

# Prevent npm from hanging in CI environments
ENV npm_config_loglevel=error \
    npm_config_progress=false \
    npm_config_update_notifier=false

# Install HTMLExtra reporter
RUN npm install -g --unsafe-perm --no-progress newman newman-reporter-htmlextra
 
WORKDIR /etc/newman

# Copy Postman collections and merge script into container.
COPY tests/postman_collection/*.json /etc/newman/
COPY tests/postman_collection/merge-collections.js /etc/newman/