# title = "Peer Backend Gitleaks Config"

[[rules]]
id = "mega-catch-all"
description = "Catch any likely secret (broad net)"
regex = '''(?i)(secret|key|token|pat|password|auth|credential|bearer|jwt|session|client)\s*[=:]\s*[A-Za-z0-9/\+=!@#$%^&*._-]{6,}|ghp_[0-9A-Za-z]{36}|xox[baprs]-[0-9]{12}-[0-9]{12}-[0-9A-Za-z]{24,}|AKIA[0-9A-Z]{16}|AIza[0-9A-Za-z\-_]{35}|eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9._-]+\.[A-Za-z0-9._-]+|-----BEGIN( RSA)? PRIVATE KEY-----'''
tags = ["key", "secret", "generic", "broad"]

[[rules]]
id = "entropy-catch-all"
description = "Catch any high-entropy random string (broad net for unknown keys)"
regex = '''[A-Za-z0-9/\+=!@#$%^&*._-]{20,}'''
entropy = 3.5
tags = ["key", "secret", "generic", "broad"]

[rules.allowlist]
description = "Ignore CLI flags, file paths, and GitHub placeholders"
regexes = [
  '''^--[a-zA-Z0-9._=-]+$''',
  '''\.gitleaks_out/.*''',
  '''^ghcr\.io/gitleaks/gitleaks.*''',
  '''^/repo/.*''',
  '''^--config=.*gitleaks\.toml$''',
  '''(?i)secrets\.[A-Za-z0-9_]+''',
  '''(?i)vars\.[A-Za-z0-9_]+''',
  '''(?i)github\.[A-Za-z0-9_]+'''
]

# --- Global Allowlist (approved exceptions ONLY) ---
[allowlist]
description = "Ignore known UUIDs and Postman test data"
regexes = [
  '''85d5f836-b1f5-4c4e-9381-1b058e13df93''',
  '''7e0b2d21-d2b0-4af5-8b73-5f8efc04b11f''',
  '''3f6d55c1-9731-4f28-8b85-5a30cd7c5cc4''',
  '''85d5f836-b1f5-4c4e-9381-1b058e13df94''',
  '''334ce5b3-813d-4fb4-86be-ac88fd63b803''',
  '''existing_advertisementId_[0-9]+''',
  '''testuser[0-9]+@example\.com'''
]

# --- Path denylist (ignore noisy generated/test files) ---
[pathDenylist]
description = "Exclude noisy generated/test files"
regexes = [
  '''^runtime-data/logs/.*''',
  '''^tests/postman_collection/.*''',
  '''^sql_files_for_import/.*''',
  '''^etc/busybox-paths\.d/.*''',
  '''^etc/ssl/openssl\.cnf(\.dist)?$'''
]
