BEGIN;

ALTER TABLE chats ALTER COLUMN name TYPE TEXT;

ALTER TABLE posts ALTER COLUMN title TYPE TEXT;
ALTER TABLE posts ALTER COLUMN mediadescription TYPE TEXT;

ALTER TABLE contactus ALTER COLUMN message TYPE TEXT;

ALTER TABLE user_reports ALTER COLUMN message TYPE TEXT;

ALTER TABLE transactions ALTER COLUMN message TYPE TEXT;

COMMIT;
