name: Build and Push Base Image

on:
  workflow_dispatch: # allow manual trigger
  push:
    paths:
      - "Dockerfile.base"
      - ".github/workflows/build_base_image.yml"

jobs:
  build-base:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # needed for GHCR push
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REPORTS_DEPLOY_TOKEN }}

      - name: Build and Push Base Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.base
          push: true
          tags: ghcr.io/peer-network/php-backend-base:latest
