# test
name: Dependabot Alerts to Discord (Scheduled)

on:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Get Dependabot Alerts
        run: |
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/${{ github.repository }}/dependabot/alerts \
          > alerts.json

          echo "Alerts:"
          cat alerts.json

      - name: Send Discord Notification
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            # Mock/test mode when manually triggered
            MESSAGE=":test_tube: **Test Dependabot Alert**\nRepo: ${{ github.repository }}\nPackage: symfony/http-foundation\nSeverity: HIGH\nAdvisory: https://github.com/advisories/GHSA-xxxx-xxxx\nFixed in: 6.4.3"
            curl -H "Content-Type: application/json" \
                 -X POST \
                 -d "{\"content\": \"$MESSAGE\"}" \
                 "$DISCORD_WEBHOOK_URL"
            exit 0
          fi

          count=$(jq length alerts.json)
          if [ "$count" -gt 0 ]; then
            MESSAGE=":rotating_light: **$count Dependabot Security Alerts Found!**"
            curl -H "Content-Type: application/json" \
                 -X POST \
                 -d "{\"content\": \"$MESSAGE\"}" \
                 "$DISCORD_WEBHOOK_URL"
          else
            echo "No alerts found."
          fi
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
