name: Dependabot Alerts to Discord

on:
  repository_vulnerability_alert:
    types: [created, reopened]

permissions:
  contents: read
  security-events: read

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          MESSAGE=":rotating_light: **Dependabot Security Alert**\n"
          MESSAGE+="Repo: ${{ github.repository }}\n"
          MESSAGE+="Package: ${{ github.event.alert.affected_package_name }}\n"
          MESSAGE+="Severity: ${{ github.event.alert.severity }}\n"
          MESSAGE+="Advisory: ${{ github.event.alert.external_reference }}\n"
          MESSAGE+="Fixed in: ${{ github.event.alert.fixed_in }}"

          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"$MESSAGE\"}" \
               "$DISCORD_WEBHOOK_URL"
